Update dependencies, build fixes
OpenMW/openmw-deps-mac pull request #39
Opened 2018-02-16 00:59 UTC by dgladkov

* Old SDL2 patch removed
* All dependencies updated to the latest version
* Added `build/` to `.gitignore`
* Bumped default OSX SDK to `macosx10.13`
* Added full sysroot path lookup from SDK name string as using just the name (e.g. `macosx10.13`) as `CMAKE_OSX_SYSROOT`/`-isysroot` didn't work for me.

2018-02-16 07:22 UTC, nikolaykasyanov commented
This is great, I'll gonna look into it during the upcoming weekend 👍 
Something should be done about boost build verbosity though, it seems Travis can't handle it.

2018-02-17 11:20 UTC, nikolaykasyanov commented
@dgladkov I guess I know why boost build fails. Image used by Travis must be changed to Xcode 9.* in order to have 10.13 SDK available.

2018-02-17 11:25 UTC, nikolaykasyanov requested changes

2018-02-17 11:25 UTC, nikolaykasyanov commented on src/CMakeLists.txt
> +  execute_process(COMMAND xcrun --show-sdk-path --sdk ${CMAKE_OSX_SYSROOT} OUTPUT_VARIABLE CMAKE_OSX_SYSROOT OUTPUT_STRIP_TRAILING_WHITESPACE)
It should be possible to fail the whole thing if `xcrun` fails. I suppose `RESULT_VARIABLE` must be passed and checked thereafter.

2018-02-17 11:25 UTC, nikolaykasyanov commented on src/CMakeLists.txt
> +if(NOT EXISTS CMAKE_OSX_SYSROOT)
Let's please make `if` style consistent (i.e. a space before `(`).

2018-02-20 21:57 UTC, dgladkov commented
Lowering number of make jobs to 2x [number of cores](https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System) seems fixed OSG build timeout, but the build time difference between different runs seems to be too big to make any solid conclusions.

2018-02-21 19:27 UTC, nikolaykasyanov commented
@dgladkov yep, it seems like Xcode 9 builds are slower (is High Sierra to blame?). Thanks for fixes!

2018-02-21 19:28 UTC, nikolaykasyanov approved these changes

2018-02-24 15:31 UTC, merged